name = "pragmarc"
description = "The PragmAda Reusable Components"
version = "1.0.0"

authors = ["Jeff Carter"]
maintainers = ["Bent Bracke <bent@bracke.dk>"]
maintainers-logins = ["bracke"]
licenses = "BSD-3-Clause"
website = "https://github.com/jrcarter/PragmARC"
tags = []
