name = "pragmarc"
description = "The PragmAda Reusable Components"
version = "1.0.0"

authors = ["Jeff Carter"]
maintainers = ["Bent Bracke <bent@bracke.dk>"]
maintainers-logins = ["bracke"]
licenses = "BSD-3-Clause"
website = "https://github.com/bracke/PragmARC"
tags = ["cards","conversions","datastructures","encryption","matching","randomness","safety","sorting","tty","containers"]

[build-switches]
"*".style_checks = "No"
"*".ada_version = "Ada12"

[[depends-on]] # Avoid bug in GNAT 13
gnat = "<13.0 | >=13.3"
